# Generated by Django 4.1.7 on 2023-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="genre_preferences",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
