# Generated by Django 4.1.7 on 2023-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.IntegerField()),
                ("book_title", models.CharField(max_length=255)),
                ("book_authors", models.CharField(max_length=255)),
                ("book_genres", models.CharField(max_length=255)),
                ("book_issue_date", models.DateField()),
            ],
        ),
    ]
