# Generated by Django 4.1.7 on 2023-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_book_book_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_authors",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_title",
            field=models.TextField(),
        ),
    ]
